export const samplePredictionsCsv = [
  [
    'Date',
    'Home',
    'Away',
    'H Win%',
    'A Win%',
    'H Proj',
    'A Proj',
    'Model Total',
    'Vegas H ML',
    'Vegas A ML',
    'H ML (model)',
    'A ML (model)',
    'ML Rec',
    'ML Edge',
    'Vegas Spread',
    'Spread Home Odds',
    'Spread Away Odds',
    'Spread Rec',
    'Recommended Spread Line',
    'Spread Edge',
    'Vegas O/U',
    'Over Odds',
    'Under Odds',
    'O/U Rec',
    'Recommended Total Line',
    'O/U Edge',
    'O/U Edge %',
  ].join(','),
  [
    '2026-03-12',
    'DUKE Duke',
    'KU Kansas',
    '62.0%',
    '38.0%',
    '80.0',
    '71.0',
    '151.0',
    '-150',
    '+130',
    '-200',
    '+170',
    'HOME',
    '+4.0%',
    '-5.5',
    '-110',
    '-110',
    'PASS',
    '',
    '',
    '145.5',
    '-110',
    '-110',
    'OVER',
    '145.5',
    '+5.5',
    '+3.5%',
  ].join(','),
].join('\n')

export const sampleResultsCsv = [
  'Date,Home,Away,Home Score,Away Score',
  '2026-03-12,DUKE,KU,78,71',
].join('\n')
